version: 3.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - development
skip_tags: true
only_commits:
  files:
    - VcRedist/**
    - tests/**
    - ci/Invoke-Tests.ps1
image: Visual Studio 2022
build: off
test_script:
- ps: . .\ci\Invoke-Tests.ps1
deploy: off
