version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: WMF 5
clone_folder: C:\Projects\VcRedist
environment:
  GitHubKey:
    secure: unWb9ORoL3oo22K6z2U2fZ+AdBmv75laNb7jibBwQCMGv9u8Cs2GayQBGjkqfPro
  NuGetApiKey:
    secure: /YPozcX4yV1XCrZuS8DAhOmH/OOjkg6+zrCTT3lHR3a7/SY7S83JNNgYBsROlLq3
  Module: VcRedist
install:
- ps: . .\ci\Install.ps1
build_script:
- ps: . .\ci\Build.ps1
test_script:
- ps: . .\ci\Tests.ps1
deploy_script:
- ps: . .\ci\Deploy.ps1

skip_commits:
  message: /AppVeyor validate.*|Merge branch 'master' of.*//

only_commits:
  files:
    - VcRedist/**/*
    - tests/**/*
    - ci/**/*
