version: 3.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - development
skip_tags: true
only_commits:
  files:
    - VcRedist/**
    - tests/**
    - ci/Invoke-Tests.ps1
    - appveyor.yml
image: Visual Studio 2022
build: off
before_test:
- ps: >-
    Import-Module "$env:APPVEYOR_BUILD_FOLDER\VcRedist" -Force

    Get-InstalledVcRedist | Uninstall-VcRedist -Confirm:$False
test_script:
- ps: . .\ci\Invoke-Tests.ps1
deploy: off
