name: PSScriptAnalyzer

on:
  push:
    branches:
      - '*'
    paths:
      - '**.ps1'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.ps1'
  workflow_dispatch:
    
jobs:
  build:
    name: psscriptanalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@2044ae068e37d0161fa2127de04c19633882f061
        with:
          path: ./VcRedist
          recurse: true 
          output: results.sarif
      
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
