name: publish-module

on:
#  workflow_dispatch:
#    branches:
#        - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v4.5
        with:
          modules-to-cache: PowerShellGet
          shell: pwsh

      # Import GPG key so that we can sign the commit
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPGKEY }}
          passphrase: ${{ secrets.GPGPASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
          git_tag_gpgsign: true
          git_push_gpgsign: false
          git_committer_name: ${{ secrets.COMMIT_NAME }}
          git_committer_email: ${{ secrets.COMMIT_EMAIL }}

      # Create release
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false

      # Push the updated module to the PowerShell Gallery
      - name: Push module to PowerShell Gallery
        shell: pwsh
        run: |
          $params = @{
              Path        = "${{ github.workspace }}/VcRedist"
              NuGetApiKey = "${{ secrets.NUGETAPIKEY }}"
              ErrorAction = "Stop"
              #WhatIf      = $True
              Verbose     = $True
          }
          Publish-Module @params
