# Automate manifest updates by checking for new versions of the VcRedist

name: UpdateManifest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '0 0 * * WED'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Create branch
      uses: peterjgrainger/action-create-branch@v2.0.0
      with:
        # The branch to create
        branch: 'UpdateManifest'
